[package]
name = 'SatayProduct'
version = '1.0.0'

[addresses]
satay_ferum_automated = "0x2"

[dependencies.satay]
git = "https://github.com/satay-protocol/satay-aptos"
rev = "main"

[dependencies.ferum]
git = "https://github.com/ferum-dex/ferum.git"
rev = "main"
subdir = "contract"
